/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        primary:         "var(--primary)",
        "primary-deep":  "var(--primary-deep)",
        "primary-soft":  "var(--primary-soft)",
        "primary-text":  "var(--primary-text)",
        "primary-glow":  "var(--primary-glow)",
        "accent-100":    "var(--accent-100)",
        "accent-200":    "var(--accent-200)",
        "accent-300":    "var(--accent-300)",
        "accent-400":    "var(--accent-400)",
        "accent-500":    "var(--accent-500)",
        "accent-600":    "var(--accent-600)",
        "accent-700":    "var(--accent-700)",
        highlight:       "var(--highlight)",
        "highlight-soft":"var(--highlight-soft)",
        canvas:          "var(--canvas)",
        surface:         "var(--surface)",
        "surface-raised":"var(--surface-raised)",
        "surface-code":  "var(--surface-code)",
        hairline:        "var(--hairline)",
        "hairline-soft": "var(--hairline-soft)",
        "hairline-strong":"var(--hairline-strong)",
        ink:             "var(--ink)",
        "ink-tint":      "var(--ink-tint)",
        charcoal:        "var(--charcoal)",
        slate:           "var(--slate)",
        steel:           "var(--steel)",
        stone:           "var(--stone)",
        muted:           "var(--muted)",
        "on-dark":       "var(--on-dark)",
        "on-dark-muted": "var(--on-dark-muted)",
        "on-surface":    "var(--on-surface)",
        "sb-bg":         "var(--sidebar-bg)",
        "sb-hover":      "var(--sidebar-hover)",
        "sb-active":     "var(--sidebar-active)",
        success:         "var(--success)",
        "success-soft":  "var(--success-soft)",
        warning:         "var(--warning)",
        "warning-soft":  "var(--warning-soft)",
        error:           "var(--error)",
        "error-soft":    "var(--error-soft)",
        info:            "var(--info)",
        "info-soft":     "var(--info-soft)",
        // Legacy aliases
        "coral":            "var(--primary)",
        "action-blue":      "var(--primary)",
        "focus-blue":       "var(--primary)",
        "error-red":        "var(--error)",
        "deep-green":       "var(--success)",
        "dark-navy":        "var(--surface-code)",
        "cohere-black":     "var(--ink)",
        "border-light":     "var(--hairline)",
        "form-focus-violet":"var(--primary)",
        "soft-coral":       "var(--primary-soft)",
        "pale-green-wash":  "var(--success-soft)",
        "pale-blue-wash":   "var(--primary-soft)",
        "muted-slate":      "var(--slate)",
        "card-border":      "var(--hairline-soft)",
        "canvas-white":     "var(--canvas)",
        "soft-stone":       "var(--surface)",
        "near-black":       "var(--ink)",
        "border-hairline":  "var(--hairline)",
      },
      fontFamily: {
        display: ['"Playfair Display"', "Georgia", "serif"],
        body:    ['"Geist"', "-apple-system", "BlinkMacSystemFont", '"Segoe UI"', "sans-serif"],
        mono:    ['"Geist Mono"', "ui-monospace", "monospace"],
      },
      borderRadius: {
        xs: "4px",
        sm: "6px",
        md: "8px",
        lg: "12px",
        xl: "16px",
        "2xl": "20px",
        full: "9999px",
      },
      fontSize: {
        "hero-display": ["84px", { lineHeight: "1.05", letterSpacing: "-1.5px" }],
        "display-lg":   ["64px", { lineHeight: "1.10", letterSpacing: "-1px" }],
        "heading-1":    ["52px", { lineHeight: "1.15", letterSpacing: "-0.5px" }],
        "heading-2":    ["36px", { lineHeight: "1.20", letterSpacing: "-0.5px" }],
        "heading-3":    ["28px", { lineHeight: "1.25", letterSpacing: "0" }],
        "heading-4":    ["22px", { lineHeight: "1.30", letterSpacing: "0" }],
        "heading-5":    ["18px", { lineHeight: "1.40", letterSpacing: "0" }],
        "subtitle":     ["18px", { lineHeight: "1.50", letterSpacing: "0" }],
        "body-md":      ["16px", { lineHeight: "1.55", letterSpacing: "0" }],
        "body-sm":      ["14px", { lineHeight: "1.50", letterSpacing: "0" }],
        "caption":      ["13px", { lineHeight: "1.40", letterSpacing: "0" }],
        "micro":        ["12px", { lineHeight: "1.40", letterSpacing: "0" }],
        "button-md":    ["14px", { lineHeight: "1.30", letterSpacing: "0" }],
        "code-md":      ["14px", { lineHeight: "1.50", letterSpacing: "0" }],
      },
      boxShadow: {
        "1": "var(--shadow-1)",
        "2": "var(--shadow-2)",
        "3": "var(--shadow-3)",
        "glow": "var(--shadow-glow)",
      },
      animation: {
        "fade-in": "fadeSlideIn 0.4s cubic-bezier(0.4, 0, 0.2, 1) forwards",
      },
    },
  },
  plugins: [],
};
